Repository centrifuge/protocol, pull requests merged in 2025-08, with the labels that each got.

#561 feat: vault factory `create2` salts
  script/VaultsDeployer.s.sol
  src/vaults/factories/AsyncVaultFactory.sol
  src/vaults/factories/SyncDepositVaultFactory.sol
  test/integration/ForkTestInvestments.sol
Labels: 👫 companion

#555 Ref: Spoke: Extract inner storage to top level contract
  snapshots/AsyncVault.json
  snapshots/SyncDepositVault.json
  snapshots/VaultRouter.json
  src/spoke/Spoke.sol
  src/spoke/interfaces/ISpoke.sol
  test/spoke/integration/BaseTest.sol
  test/spoke/integration/Spoke.t.sol
  test/spoke/unit/Spoke.t.sol
Labels: :building_construction: refactor

#566 Ref: wire adapters without using the Guardian
  script/AdaptersDeployer.s.sol
  script/WireAdapters.s.sol
  src/adapters/AxelarAdapter.sol
  src/adapters/WormholeAdapter.sol
  src/adapters/interfaces/IAxelarAdapter.sol
  src/adapters/interfaces/IWormholeAdapter.sol
  src/common/Guardian.sol
  src/common/interfaces/IGuardian.sol
  test/adapters/Deployment.t.sol
  test/adapters/unit/AxelarAdapter.t.sol
  test/adapters/unit/WormholeAdapter.t.sol
  test/common/unit/Guardian.t.sol
  test/integration/EndToEnd.t.sol
Labels: :building_construction: refactor

#582 chore: archive spell 005
  env/spell/005_arbitrum_0x1e860a8108c95be344f49ad1501fb281d8b6bfbb.sol
  env/spell/005_base_0x1e860a8108c95be344f49ad1501fb281d8b6bfbb.sol
  env/spell/005_ethereum_0x1e860a8108c95be344f49ad1501fb281d8b6bfbb.sol
  test/integration/fork/ForkTestInvestmentsV2.sol
Labels: 🪄 spell

#588 ref: hook transfer type names
  src/hooks/BaseTransferHook.sol
  src/hooks/FreelyTransferable.sol
  src/hooks/FullRestrictions.sol
  test/hooks/integration/BaseTransferHook.t.sol
  test/hooks/unit/BaseTransferHook.t.sol
Labels: :building_construction: refactor
