Repository centrifuge/protocol, pull requests merged in 2025-05, with the labels that each got.

#349 Remove hub from common dep & gateway dep
  script/VaultsDeployer.s.sol
  snapshots/AsyncVault.json
  snapshots/VaultRouter.json
  src/common/Guardian.sol
  src/common/interfaces/IGuardianActions.sol
  src/hub/Hub.sol
  src/hub/interfaces/IHub.sol
  src/vaults/BalanceSheet.sol
  test/vaults/integration/BalanceSheet.t.sol
Labels: :building_construction: refactor

#347 ref: vault & investment manager
  docs/architecture/vaults/managers.puml
  script/VaultsDeployer.s.sol
  snapshots/AsyncVault.json
  snapshots/VaultRouter.json
  src/common/MessageDispatcher.sol
  src/common/MessageProcessor.sol
  src/common/interfaces/IGatewayHandlers.sol
  src/hub/interfaces/IAccounting.sol
  src/vaults/AsyncRequestManager.sol
  src/vaults/AsyncVault.sol
  src/vaults/BaseRequestManager.sol
  src/vaults/BaseVaults.sol
  src/vaults/PoolManager.sol
  src/vaults/SyncDepositVault.sol
  src/vaults/SyncRequestManager.sol
  src/vaults/interfaces/IBaseVaults.sol
  src/vaults/interfaces/IPoolManager.sol
  src/vaults/interfaces/IVaultManager.sol
  src/vaults/interfaces/investments/IAsyncDepositManager.sol
  src/vaults/interfaces/investments/IAsyncRedeemManager.sol
  src/vaults/interfaces/investments/IAsyncRequestManager.sol
  src/vaults/interfaces/investments/IBaseRequestManager.sol
  src/vaults/interfaces/investments/IDepositManager.sol
  src/vaults/interfaces/investments/IRedeemManager.sol
  src/vaults/interfaces/investments/ISyncDepositManager.sol
  src/vaults/interfaces/investments/ISyncRequestManager.sol
  test/vaults/BaseTest.sol
  test/vaults/integration/AsyncRequestManager.t.sol
  test/vaults/integration/Deposit.t.sol
  test/vaults/integration/PoolManager.t.sol
  test/vaults/integration/SyncDeposit.t.sol
  test/vaults/integration/SyncRequestManager.t.sol
  test/vaults/unit/AsyncVault.t.sol
  test/vaults/unit/factories/TokenFactory.t.sol
Labels: :building_construction: refactor

#368 add source centrifuge chain utility to messages
  snapshots/AsyncVault.json
  snapshots/VaultRouter.json
  src/common/MessageProcessor.sol
  src/common/libraries/MessageLib.sol
  test/common/unit/libraries/MessageLib.t.sol
Labels: :building_construction: refactor

#367 fix: fulfillment grief protection
  src/hub/Hub.sol
Labels: v3

#366 Ref/remove gateway estimation
  snapshots/AsyncVault.json
  snapshots/VaultRouter.json
  src/common/Gateway.sol
  src/common/MessageDispatcher.sol
  src/common/interfaces/IGateway.sol
  src/common/interfaces/IMessageDispatcher.sol
  src/vaults/VaultRouter.sol
  src/vaults/interfaces/IVaultRouter.sol
  test/common/mocks/MockGasService.sol
  test/vaults/BaseTest.sol
  test/vaults/integration/PoolManager.t.sol
  test/vaults/integration/VaultRouter.t.sol
  test/vaults/unit/VaultRouter.t.sol
Labels: :building_construction: refactor, v3

#371 Add support for unpaid messages in the gateway
  snapshots/AsyncVault.json
  snapshots/VaultRouter.json
  src/common/Gateway.sol
  src/common/interfaces/IGateway.sol
  test/common/unit/Gateway.t.sol
Labels: :technologist: new feat

#373 Add `HubHelpers`
  script/HubDeployer.s.sol
  src/hub/Hub.sol
  src/hub/HubHelpers.sol
  src/hub/interfaces/IHubHelpers.sol
  test/hub/unit/Hub.t.sol
  test/hub/unit/HubHelpers.t.sol
Labels: :building_construction: refactor, v3

#365 fix vault claim-redeem payment
  src/vaults/VaultRouter.sol
  test/vaults/integration/VaultRouter.t.sol
Labels: :bug: bug

#374 ref: remove deprecated gateway msgs
  snapshots/AsyncVault.json
  snapshots/VaultRouter.json
  src/common/libraries/MessageLib.sol
Labels: :building_construction: refactor, v3

#345 Add source chain ID checks, change share transfers into two-step process
  script/VaultsDeployer.s.sol
  snapshots/AsyncVault.json
  snapshots/VaultRouter.json
  src/common/Gateway.sol
  src/common/MessageDispatcher.sol
  src/common/MessageProcessor.sol
  src/common/interfaces/IGateway.sol
  src/common/interfaces/IGatewayHandlers.sol
  src/common/interfaces/IGatewaySenders.sol
  src/common/interfaces/IMessageProcessor.sol
  src/common/libraries/MessageLib.sol
  src/hub/Hub.sol
  src/hub/interfaces/IHub.sol
  src/vaults/PoolManager.sol
  src/vaults/SyncRequestManager.sol
  test/common/unit/Gateway.t.sol
  test/common/unit/libraries/MessageLib.t.sol
  test/vaults/integration/PoolManager.t.sol
  test/vaults/mocks/MockCentrifugeChain.sol
Labels: v3

#391 Fix: Correct check before disputeRecovery
  src/common/adapters/MultiAdapter.sol
  test/common/unit/MultiAdapter.t.sol
Labels: :bug: bug

#388 Missing renames from Vaults to spoke
  docs/architecture/deployers.puml
  docs/architecture/spokes/managers.puml
  docs/architecture/spokes/overview.puml
  docs/architecture/spokes/vaults.puml
  script/FullDeployer.s.sol
  script/SpokeDeployer.s.sol
  test/integration/EndToEnd.t.sol
  test/spokes/BaseTest.sol
Labels: :building_construction: refactor

#394 Ref: UpdateVault as independent message
  script/adapters/Localhost.s.sol
  snapshots/AsyncVault.json
  snapshots/VaultRouter.json
  src/common/MessageDispatcher.sol
  src/common/MessageProcessor.sol
  src/common/interfaces/IGatewayHandlers.sol
  src/common/interfaces/IGatewaySenders.sol
  src/common/libraries/MessageLib.sol
  src/hub/Hub.sol
  src/hub/interfaces/IHub.sol
  src/spoke/Spoke.sol
  test/common/unit/libraries/MessageLib.t.sol
  test/hub/integration/Cases.t.sol
  test/hub/unit/Hub.t.sol
  test/integration/EndToEnd.t.sol
  test/spoke/BaseTest.sol
  test/spoke/integration/Spoke.t.sol
  test/spoke/mocks/MockCentrifugeChain.sol
Labels: :building_construction: refactor

#396 Fix: TransferShares issue
  snapshots/VaultRouter.json
  src/common/MessageDispatcher.sol
  src/common/interfaces/IGatewaySenders.sol
  src/hub/Hub.sol
  src/spoke/Spoke.sol
Labels: :bug: bug, :building_construction: refactor

#400 Tests: EndToEnd additions
  script/HubDeployer.s.sol
  script/adapters/Localhost.s.sol
  src/hub/Hub.sol
  src/hub/ShareClassManager.sol
  src/hub/interfaces/IHub.sol
  src/hub/interfaces/IShareClassManager.sol
  src/spoke/vaults/SyncRequestManager.sol
  test/hub/integration/BatchingAndPayment.t.sol
  test/hub/integration/Cases.t.sol
  test/hub/unit/Hub.t.sol
  test/hub/unit/ShareClassManager.t.sol
  test/integration/EndToEnd.t.sol
Labels: :building_construction: refactor, :white_check_mark: test

#405 File reorganization (spoke and vaults modules)
  .github/workflows/ci.yml
  deployments/verify.sh
  foundry.toml
  script/SpokeDeployer.s.sol
  script/adapters/Localhost.s.sol
  src/common/interfaces/IValuation.sol
  src/spoke/BalanceSheet.sol
  src/spoke/Spoke.sol
  src/spoke/factories/PoolEscrowFactory.sol
  src/spoke/factories/TokenFactory.sol
  src/spoke/factories/interfaces/IPoolEscrowFactory.sol
  src/spoke/factories/interfaces/ITokenFactory.sol
  src/spoke/factories/interfaces/IVaultFactory.sol
  src/spoke/interfaces/IBalanceSheet.sol
  src/spoke/interfaces/ISpoke.sol
  src/spoke/interfaces/investments/IAsyncDepositManager.sol
  src/spoke/interfaces/investments/IAsyncRedeemManager.sol
  src/spoke/interfaces/investments/IAsyncRequestManager.sol
  src/spoke/interfaces/investments/IDepositManager.sol
  src/spoke/interfaces/investments/IRedeemManager.sol
  src/spoke/interfaces/investments/ISyncDepositManager.sol
  src/spoke/interfaces/investments/ISyncRequestManager.sol
  src/spoke/interfaces/vaults/IBaseVaults.sol
  src/spoke/vaults/AsyncRequestManager.sol
  src/spoke/vaults/AsyncVault.sol
  src/spoke/vaults/BaseRequestManager.sol
  src/spoke/vaults/BaseVaults.sol
  src/spoke/vaults/SyncDepositVault.sol
  src/spoke/vaults/SyncRequestManager.sol
  src/spoke/vaults/VaultRouter.sol
  src/spoke/vaults/factories/AsyncVaultFactory.sol
  src/spoke/vaults/factories/SyncDepositVaultFactory.sol
  src/spoke/vaults/interfaces/IAsyncVault.sol
  src/spoke/vaults/interfaces/IBaseRequestManager.sol
  src/spoke/vaults/interfaces/IBaseVault.sol
  src/spoke/vaults/interfaces/IVaultManagers.sol
  src/spoke/vaults/interfaces/IVaultRouter.sol
  src/spoke/vaults/legacy/LegacyVaultAdapter.sol
  src/spoke/vaults/legacy/interfaces/IInvestmentManager.sol
  src/spoke/vaults/legacy/interfaces/ILegacyVault.sol
  src/spoke/vaults/legacy/interfaces/ILegacyVaultAdapter.sol
  test/hooks/integration/FreelyTransferable.t.sol
  test/integration/EndToEnd.t.sol
  test/spoke/BaseTest.sol
  test/spoke/integration/AsyncRequestManager.t.sol
  test/spoke/integration/Deposit.t.sol
  test/spoke/integration/Operator.t.sol
  test/spoke/integration/Redeem.t.sol
  test/spoke/integration/Spoke.t.sol
  test/spoke/integration/SyncDeposit.t.sol
  test/spoke/integration/SyncRequestManager.t.sol
  test/spoke/integration/VaultRouter.t.sol
  test/spoke/mocks/MockCentrifugeChain.sol
  test/spoke/unit/AsyncVault.t.sol
  test/spoke/unit/VaultRouter.t.sol
  test/spoke/unit/factories/PoolEscrowFactory.t.sol
  test/spoke/unit/factories/TokenFactory.t.sol
Labels: :building_construction: refactor, v3

#398 fix: blocked requests edge case
  src/hub/Hub.sol
  src/hub/ShareClassManager.sol
  src/hub/interfaces/IHub.sol
  src/hub/interfaces/IShareClassManager.sol
  test/hub/unit/Hub.t.sol
  test/hub/unit/ShareClassManager.t.sol
Labels: :bug: bug, v3

#414 Ref: Remove all trigger methods
  snapshots/AsyncVault.json
  snapshots/SyncDepositVault.json
  snapshots/VaultRouter.json
  src/common/MessageDispatcher.sol
  src/common/MessageProcessor.sol
  src/common/interfaces/IGatewayHandlers.sol
  src/common/interfaces/IGatewaySenders.sol
  src/hub/Hub.sol
  src/hub/interfaces/IHub.sol
  src/spoke/BalanceSheet.sol
  src/spoke/interfaces/IBalanceSheet.sol
  test/hub/unit/Hub.t.sol
Labels: :building_construction: refactor
