Repository centrifuge/protocol, pull requests merged in 2025-04, with the labels that each got.

#213 fix: ShareClassId collision
  src/common/types/ShareClassId.sol
  test/pools/unit/MultiShareClass.t.sol
  test/pools/unit/types/ShareClassId.t.sol
Labels: :bug: bug

#201 feat: add queued requests to `MultiShareClass`
  .forge-snapshots/AsyncRequests_fulfillDepositRequest.snap
  src/pools/Hub.sol
  src/pools/MultiShareClass.sol
  src/pools/interfaces/IMultiShareClass.sol
  src/pools/interfaces/IShareClassManager.sol
  test/pools/unit/MultiShareClass.t.sol
  test/vaults/integration/AsyncRequests.t.sol
Labels: :technologist: new feat

#215 Cleaning stuff gateway related
  .forge-snapshots/VaultRouter_requestDeposit.snap
  .forge-snapshots/VaultRouter_requestRedeem.snap
  .forge-snapshots/VaultRouter_transferShares.snap
  src/common/Gateway.sol
  src/common/interfaces/IGateway.sol
  src/pools/Hub.sol
  src/vaults/VaultRouter.sol
  test/common/unit/Gateway.t.sol
  test/pools/integration/BatchingAndPayment.t.sol
  test/pools/integration/Cases.t.sol
  test/vaults/integration/Admin.t.sol
  test/vaults/integration/VaultRouter.t.sol
  test/vaults/unit/VaultRouter.t.sol
Labels: :building_construction: refactor

#221 Rename chainId to centrifugeId
  .forge-snapshots/AsyncVault_requestDeposit.snap
  .forge-snapshots/VaultRouter_requestDeposit.snap
  .forge-snapshots/VaultRouter_requestRedeem.snap
  .forge-snapshots/VaultRouter_transferShares.snap
  script/CommonDeployer.s.sol
  script/FullDeployer.s.sol
  script/PoolsDeployer.s.sol
  script/VaultsDeployer.s.sol
  script/adapters/Localhost.s.sol
  script/adapters/Wormhole.s.sol
  src/common/AxelarAdapter.sol
  src/common/Gateway.sol
  src/common/Guardian.sol
  src/common/MessageDispatcher.sol
  src/common/MessageProcessor.sol
  src/common/WormholeAdapter.sol
  src/common/interfaces/IAdapter.sol
  src/common/interfaces/IAxelarAdapter.sol
  src/common/interfaces/IGasService.sol
  src/common/interfaces/IGateway.sol
  src/common/interfaces/IGatewayHandlers.sol
  src/common/interfaces/IGatewaySenders.sol
  src/common/interfaces/IGuardian.sol
  src/common/interfaces/IMessageHandler.sol
  src/common/interfaces/IMessageSender.sol
  src/common/interfaces/IWormholeAdapter.sol
  src/common/libraries/MessageLib.sol
  src/common/types/AssetId.sol
  src/common/types/PoolId.sol
  src/pools/AssetRegistry.sol
  src/pools/Hub.sol
  src/pools/PoolRegistry.sol
  src/pools/interfaces/IHub.sol
  src/pools/interfaces/IPoolRegistry.sol
  src/vaults/PoolManager.sol
  src/vaults/VaultRouter.sol
  src/vaults/interfaces/IPoolManager.sol
  src/vaults/interfaces/IVaultRouter.sol
  test/common/unit/WormholeAdapter.t.sol
  test/common/unit/libraries/MessageLib.t.sol
  test/integration/adapters/LocalAdapter.sol
  test/pools/mocks/MockVaults.sol
  test/pools/unit/PoolRegistry.t.sol
  test/pools/unit/types/AssetId.t.sol
  test/pools/unit/types/PoolId.t.sol
  test/vaults/BaseTest.sol
  test/vaults/fuzzing/recon-aggregator/TargetFunctions.sol
  test/vaults/fuzzing/recon-aggregator/targets/BiasedTargetFunctions.sol
  test/vaults/fuzzing/recon-core/targets/GatewayMockFunctions.sol
  test/vaults/fuzzing/recon-core/targets/PoolManagerFunctions.sol
  test/vaults/integration/BalanceSheet.t.sol
  test/vaults/integration/PoolManager.t.sol
  test/vaults/unit/VaultRouter.t.sol
Labels: :building_construction: refactor

#225 Ref/pools to hub
  foundry.toml
  script/FullDeployer.s.sol
  script/HubDeployer.s.sol
  script/adapters/Axelar.s.sol
  script/adapters/Localhost.s.sol
  script/adapters/Wormhole.s.sol
  src/common/Guardian.sol
  src/hub/Accounting.sol
  src/hub/Holdings.sol
  src/hub/Hub.sol
  src/hub/HubRegistry.sol
  src/hub/ShareClassManager.sol
  src/hub/interfaces/IAccounting.sol
  src/hub/interfaces/IHoldings.sol
  src/hub/interfaces/IHub.sol
  src/hub/interfaces/IHubRegistry.sol
  src/hub/interfaces/IShareClassManager.sol
  src/vaults/interfaces/IVaultRouter.sol
  test/common/types/AccountId.t.sol
  test/common/types/AssetId.t.sol
  test/common/types/PoolId.t.sol
  test/common/types/ShareClassId.t.sol
  test/hub/integration/BaseTest.sol
  test/hub/integration/BatchingAndPayment.t.sol
  test/hub/integration/Cases.t.sol
  test/hub/mocks/MockVaults.sol
  test/hub/unit/Accounting.t.sol
  test/hub/unit/Holdings.t.sol
  test/hub/unit/Hub.t.sol
  test/hub/unit/HubRegistry.t.sol
  test/hub/unit/MultiShareClass.t.sol
  test/integration/EndToEnd.t.sol
Labels: :building_construction: refactor

#227 Unify recoverTokens method, send the message, add TokenRecoverer
  script/CommonDeployer.s.sol
  snapshots/AsyncVault.json
  snapshots/VaultRouter.json
  src/common/Gateway.sol
  src/common/Guardian.sol
  src/common/MessageDispatcher.sol
  src/common/MessageProcessor.sol
  src/common/Root.sol
  src/common/TokenRecoverer.sol
  src/common/interfaces/IGatewaySenders.sol
  src/common/interfaces/IGuardian.sol
  src/common/interfaces/IRoot.sol
  src/common/interfaces/ITokenRecoverer.sol
  src/hub/Hub.sol
  src/misc/Recoverable.sol
  src/misc/interfaces/IRecoverable.sol
  src/vaults/AsyncRequests.sol
  src/vaults/BalanceSheet.sol
  src/vaults/BaseInvestmentManager.sol
  src/vaults/BaseVaults.sol
  src/vaults/PoolManager.sol
  src/vaults/VaultRouter.sol
  src/vaults/interfaces/IERC7540.sol
  src/vaults/interfaces/IPoolManager.sol
  src/vaults/interfaces/IVaultRouter.sol
  src/vaults/interfaces/investments/IBaseInvestmentManager.sol
  test/common/unit/Gateway.t.sol
  test/common/unit/TokenRecoverer.t.sol
  test/misc/unit/Recoverable.t.sol
  test/vaults/integration/Admin.t.sol
  test/vaults/integration/BalanceSheet.t.sol
  test/vaults/integration/PoolManager.t.sol
  test/vaults/unit/VaultRouter.t.sol
Labels: :technologist: new feat, :building_construction: refactor

#230 Fix issue with Gateway proofs
  snapshots/AsyncVault.json
  snapshots/VaultRouter.json
  src/common/Gateway.sol
Labels: :bug: bug

#184 Feat: Update prices of Share Class
  script/adapters/Localhost.s.sol
  snapshots/AsyncVault.json
  snapshots/VaultRouter.json
  src/common/MessageDispatcher.sol
  src/common/MessageProcessor.sol
  src/common/interfaces/IGatewayHandlers.sol
  src/common/interfaces/IGatewaySenders.sol
  src/common/libraries/MessageLib.sol
  src/hub/Hub.sol
  src/hub/ShareClassManager.sol
  src/hub/interfaces/IHoldings.sol
  src/hub/interfaces/IHub.sol
  src/hub/interfaces/IHubRegistry.sol
  src/hub/interfaces/IShareClassManager.sol
  src/misc/TransientValuation.sol
  src/misc/libraries/ConversionLib.sol
  src/misc/libraries/MathLib.sol
  src/misc/types/D18.sol
  src/vaults/AsyncRequests.sol
  src/vaults/BalanceSheet.sol
  src/vaults/BaseInvestmentManager.sol
  src/vaults/PoolManager.sol
  src/vaults/SyncRequests.sol
  src/vaults/interfaces/IBalanceSheet.sol
  src/vaults/interfaces/IERC7540.sol
  src/vaults/interfaces/IPoolManager.sol
  src/vaults/interfaces/investments/ISyncRequests.sol
  src/vaults/libraries/VaultPricingLib.sol
  test/common/unit/libraries/MessageLib.t.sol
  test/hooks/integration/FreelyTransferable.t.sol
  test/hub/integration/BaseTest.sol
  test/hub/integration/Cases.t.sol
  test/hub/mocks/MockVaults.sol
  test/hub/unit/Hub.t.sol
  test/hub/unit/ShareClassManager.t.sol
  test/misc/unit/libraries/D18.t.sol
  test/misc/unit/libraries/MathLib.t.sol
  test/vaults/BaseTest.sol
  test/vaults/fuzzing/recon-core/targets/GatewayMockFunctions.sol
  test/vaults/integration/AssetShareConversion.t.sol
  test/vaults/integration/AsyncRequests.t.sol
  test/vaults/integration/Deposit.t.sol
  test/vaults/integration/DepositRedeem.t.sol
  test/vaults/integration/Operator.t.sol
  test/vaults/integration/PoolManager.t.sol
  test/vaults/integration/Redeem.t.sol
  test/vaults/integration/SyncDeposit.t.sol
  test/vaults/integration/SyncRequests.t.sol
  test/vaults/mocks/MockCentrifugeChain.sol
Labels: :technologist: new feat

#237 Fix gateway refund payment
  snapshots/AsyncVault.json
  snapshots/VaultRouter.json
  src/common/Gateway.sol
  src/common/interfaces/IGateway.sol
  src/hub/Hub.sol
  src/vaults/VaultRouter.sol
  test/common/unit/Gateway.t.sol
Labels: annoyance

#253 Gateway unify payment
  script/CommonDeployer.s.sol
  script/adapters/Localhost.s.sol
  script/adapters/Wormhole.s.sol
  snapshots/AsyncVault.json
  snapshots/VaultRouter.json
  src/common/GasService.sol
  src/common/Gateway.sol
  src/common/MessageDispatcher.sol
  src/common/MessageProcessor.sol
  src/common/WormholeAdapter.sol
  src/common/interfaces/IGasService.sol
  src/common/interfaces/IGateway.sol
  src/common/interfaces/IMessageProperties.sol
  src/common/interfaces/IWormholeAdapter.sol
  test/common/mocks/MockGasService.sol
  test/common/unit/GasService.t.sol
  test/common/unit/Gateway.t.sol
  test/common/unit/WormholeAdapter.t.sol
  test/hub/integration/BaseTest.sol
  test/integration/EndToEnd.t.sol
  test/vaults/BaseTest.sol
  test/vaults/integration/Deposit.t.sol
  test/vaults/integration/VaultRouter.t.sol
  test/vaults/unit/VaultRouter.t.sol
Labels: :building_construction: refactor

#239 Refactor createHoldings
  foundry.toml
  script/adapters/Localhost.s.sol
  src/common/types/AccountId.sol
  src/hub/Accounting.sol
  src/hub/Holdings.sol
  src/hub/Hub.sol
  src/hub/interfaces/IAccounting.sol
  src/hub/interfaces/IHoldings.sol
  src/hub/interfaces/IHub.sol
  test/common/types/AccountId.t.sol
  test/hub/integration/BaseTest.sol
  test/hub/integration/Cases.t.sol
  test/hub/unit/Accounting.t.sol
  test/hub/unit/Holdings.t.sol
  test/hub/unit/Hub.t.sol
Labels: v3: pre-audit

#264 Ref. minor journal simplification
  snapshots/AsyncVault.json
  snapshots/VaultRouter.json
  src/common/Gateway.sol
  src/hub/Accounting.sol
  src/hub/Hub.sol
  src/hub/interfaces/IAccounting.sol
  src/vaults/BalanceSheet.sol
Labels: :building_construction: refactor

#263 Ref: Give contract support to create3
  script/CommonDeployer.s.sol
  script/VaultsDeployer.s.sol
  src/common/Gateway.sol
  src/vaults/AsyncRequests.sol
  src/vaults/BalanceSheet.sol
  src/vaults/BaseInvestmentManager.sol
  src/vaults/PoolManager.sol
  src/vaults/SyncRequests.sol
  src/vaults/VaultRouter.sol
  src/vaults/factories/AsyncVaultFactory.sol
  src/vaults/factories/SyncDepositVaultFactory.sol
  test/common/unit/Gateway.t.sol
  test/vaults/fuzzing/recon-aggregator/Setup.sol
  test/vaults/fuzzing/recon-core/Setup.sol
  test/vaults/integration/AsyncRequests.t.sol
  test/vaults/integration/BalanceSheet.t.sol
  test/vaults/integration/PoolManager.t.sol
  test/vaults/integration/SyncRequests.t.sol
  test/vaults/unit/VaultRouter.t.sol
Labels: :building_construction: refactor

#268 Gateway UTs and fixes
  snapshots/AsyncVault.json
  snapshots/VaultRouter.json
  src/common/AxelarAdapter.sol
  src/common/Gateway.sol
  src/common/MessageProcessor.sol
  src/common/WormholeAdapter.sol
  src/common/interfaces/IAdapter.sol
  src/common/interfaces/IGateway.sol
  src/common/interfaces/IMessageProperties.sol
  src/common/libraries/MessageLib.sol
  src/common/libraries/MessageProofLib.sol
  src/hub/Accounting.sol
  src/misc/TransientValuation.sol
  src/misc/libraries/TransientArrayLib.sol
  src/misc/libraries/TransientBytesLib.sol
  src/misc/libraries/TransientStorage.sol
  src/misc/libraries/TransientStorageLib.sol
  test/common/mocks/MockAdapter.sol
  test/common/unit/Gateway.t.sol
  test/common/unit/libraries/MessageLib.t.sol
  test/common/unit/libraries/MessageProofLib.t.sol
  test/hub/mocks/MockVaults.sol
  test/integration/adapters/LocalAdapter.sol
  test/misc/unit/libraries/TransientArray.t.sol
  test/misc/unit/libraries/TransientBytesLib.t.sol
  test/vaults/fuzzing/recon-aggregator/targets/BiasedTargetFunctions.sol
  test/vaults/integration/Admin.t.sol
  test/vaults/mocks/MockCentrifugeChain.sol
Labels: :bug: bug, :building_construction: refactor, :white_check_mark: test

#279 Gateway: renamings to more accurate names
  snapshots/VaultRouter.json
  src/common/Gateway.sol
  src/common/Guardian.sol
  src/common/MessageDispatcher.sol
  src/common/MessageProcessor.sol
  src/common/interfaces/IGateway.sol
  src/common/interfaces/IGatewayHandlers.sol
  src/common/interfaces/IGatewaySenders.sol
  src/common/interfaces/IGuardian.sol
  src/common/libraries/MessageLib.sol
  test/common/unit/Gateway.t.sol
  test/common/unit/libraries/MessageLib.t.sol
  test/vaults/fuzzing/recon-aggregator/TargetFunctions.sol
  test/vaults/fuzzing/recon-aggregator/targets/BiasedTargetFunctions.sol
  test/vaults/integration/Admin.t.sol
Labels: :building_construction: refactor

#278 Feat: add transient bytes append
  src/common/Gateway.sol
  src/misc/libraries/TransientBytesLib.sol
  test/misc/unit/libraries/TransientBytesLib.t.sol
Labels: :technologist: new feat

#280 Ref/pending renames
  src/hub/Holdings.sol
  src/hub/Hub.sol
  src/hub/interfaces/IHoldings.sol
  src/hub/interfaces/IHub.sol
  src/misc/BaseValuation.sol
  src/misc/ERC20.sol
  src/misc/interfaces/IBaseValuation.sol
  src/misc/libraries/BytesLib.sol
  src/vaults/interfaces/token/IShareToken.sol
  test/common/unit/Gateway.t.sol
  test/hub/unit/Holdings.t.sol
  test/misc/unit/BaseValuation.t.sol
  test/misc/unit/ERC20.t.sol
  test/vaults/unit/token/ShareToken.t.sol
Labels: :building_construction: refactor

#266 Feat: Refund per escrow
  script/VaultsDeployer.s.sol
  snapshots/AsyncVault.json
  snapshots/VaultRouter.json
  src/common/Gateway.sol
  src/common/interfaces/IGateway.sol
  src/misc/Recoverable.sol
  src/misc/interfaces/IRecoverable.sol
  src/vaults/AsyncRequests.sol
  src/vaults/BalanceSheet.sol
  src/vaults/Escrow.sol
  src/vaults/PoolManager.sol
  src/vaults/factories/PoolEscrowFactory.sol
  src/vaults/interfaces/IEscrow.sol
  test/common/unit/Gateway.t.sol
  test/vaults/integration/Deposit.t.sol
  test/vaults/unit/Escrow.t.sol
  test/vaults/unit/factories/PoolEscrowFactory.t.sol
Labels: :technologist: new feat

#283 Add PoolId and ShareClassId types to IUpdateContract
  snapshots/AsyncVault.json
  snapshots/VaultRouter.json
  src/vaults/BalanceSheet.sol
  src/vaults/PoolManager.sol
  src/vaults/SyncRequests.sol
  src/vaults/interfaces/IUpdateContract.sol
  test/vaults/BaseTest.sol
  test/vaults/integration/BalanceSheet.t.sol
  test/vaults/integration/PoolManager.t.sol
  test/vaults/integration/SyncRequests.t.sol
Labels: :building_construction: refactor

#282 Fix: clean up misc v1
  script/VaultsDeployer.s.sol
  snapshots/AsyncVault.json
  snapshots/VaultRouter.json
  src/hub/Accounting.sol
  src/hub/Holdings.sol
  src/hub/Hub.sol
  src/hub/interfaces/IAccounting.sol
  src/hub/interfaces/IHoldings.sol
  src/vaults/AsyncRequests.sol
  test/hub/integration/BaseTest.sol
  test/hub/integration/Cases.t.sol
  test/hub/unit/Accounting.t.sol
  test/hub/unit/Holdings.t.sol
  test/vaults/integration/AsyncRequests.t.sol
Labels: v3: pre-audit

#288 Remove fuzzing tests temporaly
  test/vaults/fuzzing/recon-aggregator/BeforeAfter.sol
  test/vaults/fuzzing/recon-aggregator/CryticAggregatorTester.sol
  test/vaults/fuzzing/recon-aggregator/CryticToFoundry.sol
  test/vaults/fuzzing/recon-aggregator/Properties.sol
  test/vaults/fuzzing/recon-aggregator/Setup.sol
  test/vaults/fuzzing/recon-aggregator/TargetFunctions.sol
  test/vaults/fuzzing/recon-aggregator/debug/CryticToFoundryAggregator.sol
  test/vaults/fuzzing/recon-aggregator/medusa-aggregator.json
  test/vaults/fuzzing/recon-aggregator/targets/BiasedTargetFunctions.sol
  test/vaults/fuzzing/recon-core/AsyncVaultCentrifugeProperties.sol
  test/vaults/fuzzing/recon-core/AsyncVaultProperties.sol
  test/vaults/fuzzing/recon-core/CryticTester.sol
  test/vaults/fuzzing/recon-core/CryticToFoundry.sol
  test/vaults/fuzzing/recon-core/Properties.sol
  test/vaults/fuzzing/recon-core/Setup.sol
  test/vaults/fuzzing/recon-core/SharedStorage.sol
  test/vaults/fuzzing/recon-core/TargetFunctions.sol
  test/vaults/fuzzing/recon-core/echidna.yaml
  test/vaults/fuzzing/recon-core/helpers/CallTestAndUndo.sol
  test/vaults/fuzzing/recon-core/medusa-core.json
  test/vaults/fuzzing/recon-core/targets/GatewayMockFunctions.sol
  test/vaults/fuzzing/recon-core/targets/PoolManagerFunctions.sol
  test/vaults/fuzzing/recon-core/targets/RestrictedTransfersFunctions.sol
  test/vaults/fuzzing/recon-core/targets/ShareTokenFunctions.sol
  test/vaults/fuzzing/recon-core/targets/TargetSwitchingFunctions.sol
  test/vaults/fuzzing/recon-core/targets/VaultCallbacks.sol
  test/vaults/fuzzing/recon-core/targets/VaultFunctions.sol
Labels: :white_check_mark: test

#289 Ref Add custom types to PoolManager
  script/adapters/Localhost.s.sol
  snapshots/AsyncVault.json
  snapshots/VaultRouter.json
  src/common/MessageDispatcher.sol
  src/common/interfaces/IGatewaySenders.sol
  src/vaults/AsyncRequests.sol
  src/vaults/BalanceSheet.sol
  src/vaults/BaseInvestmentManager.sol
  src/vaults/PoolManager.sol
  src/vaults/SyncRequests.sol
  src/vaults/VaultRouter.sol
  src/vaults/interfaces/IPoolManager.sol
  test/integration/EndToEnd.t.sol
  test/vaults/BaseTest.sol
  test/vaults/integration/AssetShareConversion.t.sol
  test/vaults/integration/BalanceSheet.t.sol
  test/vaults/integration/Deposit.t.sol
  test/vaults/integration/DepositRedeem.t.sol
  test/vaults/integration/PoolManager.t.sol
  test/vaults/integration/Redeem.t.sol
  test/vaults/integration/SyncRequests.t.sol
  test/vaults/integration/VaultRouter.t.sol
  test/vaults/mocks/MockCentrifugeChain.sol
  test/vaults/unit/AsyncVault.t.sol
Labels: :building_construction: refactor

#292 Ref: PoolId ShareClassId and AssetId in vaults and investment managers
  snapshots/AsyncVault.json
  snapshots/VaultRouter.json
  src/vaults/AsyncRequests.sol
  src/vaults/AsyncVault.sol
  src/vaults/BalanceSheet.sol
  src/vaults/BaseInvestmentManager.sol
  src/vaults/BaseVaults.sol
  src/vaults/PoolManager.sol
  src/vaults/SyncDepositVault.sol
  src/vaults/SyncRequests.sol
  src/vaults/factories/AsyncVaultFactory.sol
  src/vaults/factories/SyncDepositVaultFactory.sol
  src/vaults/interfaces/IERC7540.sol
  src/vaults/interfaces/IVaultManager.sol
  src/vaults/interfaces/factories/IAsyncVaultFactory.sol
  src/vaults/interfaces/factories/IVaultFactory.sol
  src/vaults/interfaces/investments/ISharePriceProvider.sol
  src/vaults/interfaces/investments/ISyncRequests.sol
  src/vaults/legacy/LegacyVaultAdapter.sol
  test/hooks/integration/FreelyTransferable.t.sol
  test/vaults/BaseTest.sol
  test/vaults/integration/Burn.t.sol
  test/vaults/integration/Deposit.t.sol
  test/vaults/integration/Mint.t.sol
  test/vaults/integration/Operator.t.sol
  test/vaults/integration/PoolManager.t.sol
  test/vaults/integration/Redeem.t.sol
  test/vaults/integration/SyncDeposit.t.sol
  test/vaults/integration/SyncRequests.t.sol
  test/vaults/integration/VaultRouter.t.sol
  test/vaults/unit/AsyncVault.t.sol
  test/vaults/unit/VaultRouter.t.sol
Labels: :building_construction: refactor

#294 Ref: PoolId and ShareClassId in escrows and router
  snapshots/AsyncVault.json
  snapshots/VaultRouter.json
  src/vaults/AsyncRequests.sol
  src/vaults/AsyncVault.sol
  src/vaults/BalanceSheet.sol
  src/vaults/BaseVaults.sol
  src/vaults/Escrow.sol
  src/vaults/PoolManager.sol
  src/vaults/SyncRequests.sol
  src/vaults/VaultRouter.sol
  src/vaults/factories/PoolEscrowFactory.sol
  src/vaults/interfaces/IEscrow.sol
  src/vaults/interfaces/IVaultRouter.sol
  src/vaults/interfaces/factories/IPoolEscrowFactory.sol
  src/vaults/legacy/LegacyVaultAdapter.sol
  test/vaults/integration/BalanceSheet.t.sol
  test/vaults/integration/Deposit.t.sol
  test/vaults/integration/PoolManager.t.sol
  test/vaults/integration/Redeem.t.sol
  test/vaults/integration/VaultRouter.t.sol
  test/vaults/mocks/MockCentrifugeChain.sol
  test/vaults/unit/Escrow.t.sol
  test/vaults/unit/VaultRouter.t.sol
  test/vaults/unit/factories/PoolEscrowFactory.t.sol
Labels: :building_construction: refactor

#295 Organize some vault interface files and imports
  script/adapters/Localhost.s.sol
  src/hooks/FreelyTransferable.sol
  src/hooks/RestrictedTransfers.sol
  src/misc/interfaces/IERC7540.sol
  src/misc/interfaces/IERC7575.sol
  src/vaults/AsyncRequests.sol
  src/vaults/AsyncVault.sol
  src/vaults/BaseInvestmentManager.sol
  src/vaults/BaseVaults.sol
  src/vaults/PoolManager.sol
  src/vaults/SyncDepositVault.sol
  src/vaults/SyncRequests.sol
  src/vaults/VaultRouter.sol
  src/vaults/interfaces/IBaseVaults.sol
  src/vaults/interfaces/token/IHook.sol
  src/vaults/interfaces/token/IShareToken.sol
  src/vaults/legacy/LegacyVaultAdapter.sol
  src/vaults/legacy/interfaces/ILegacyVault.sol
  src/vaults/libraries/VaultPricingLib.sol
  src/vaults/token/ShareToken.sol
  test/vaults/integration/AsyncRequests.t.sol
  test/vaults/integration/Deposit.t.sol
  test/vaults/integration/Operator.t.sol
  test/vaults/integration/PoolManager.t.sol
  test/vaults/integration/Redeem.t.sol
  test/vaults/integration/VaultRouter.t.sol
  test/vaults/mocks/MockHook.sol
  test/vaults/unit/AsyncVault.t.sol
  test/vaults/unit/VaultRouter.t.sol
  test/vaults/unit/token/RestrictedTransfers.t.sol
  test/vaults/unit/token/ShareToken.t.sol
Labels: :building_construction: refactor

#297 Ref: Factory addresss typed
  script/VaultsDeployer.s.sol
  src/hooks/Permissionless.sol
  src/vaults/AsyncVault.sol
  src/vaults/BaseVaults.sol
  src/vaults/PoolManager.sol
  src/vaults/SyncDepositVault.sol
  src/vaults/VaultRouter.sol
  src/vaults/factories/AsyncVaultFactory.sol
  src/vaults/factories/PoolEscrowFactory.sol
  src/vaults/factories/SyncDepositVaultFactory.sol
  src/vaults/interfaces/IPoolManager.sol
  src/vaults/interfaces/factories/IPoolEscrowFactory.sol
  src/vaults/interfaces/factories/IVaultFactory.sol
  src/vaults/legacy/LegacyVaultAdapter.sol
  test/vaults/BaseTest.sol
  test/vaults/integration/PoolManager.t.sol
  test/vaults/integration/SyncRequests.t.sol
  test/vaults/unit/VaultRouter.t.sol
Labels: :building_construction: refactor

#298 Ref: typed vaults
  snapshots/AsyncVault.json
  snapshots/VaultRouter.json
  src/vaults/AsyncRequests.sol
  src/vaults/AsyncVault.sol
  src/vaults/BaseInvestmentManager.sol
  src/vaults/BaseVaults.sol
  src/vaults/PoolManager.sol
  src/vaults/SyncRequests.sol
  src/vaults/VaultRouter.sol
  src/vaults/factories/AsyncVaultFactory.sol
  src/vaults/factories/SyncDepositVaultFactory.sol
  src/vaults/interfaces/IPoolManager.sol
  src/vaults/interfaces/IVaultManager.sol
  src/vaults/interfaces/IVaultRouter.sol
  src/vaults/interfaces/factories/IVaultFactory.sol
  src/vaults/interfaces/investments/IAsyncDepositManager.sol
  src/vaults/interfaces/investments/IAsyncRedeemManager.sol
  src/vaults/interfaces/investments/IAsyncRequests.sol
  src/vaults/interfaces/investments/IBaseInvestmentManager.sol
  src/vaults/interfaces/investments/IDepositManager.sol
  src/vaults/interfaces/investments/IRedeemManager.sol
  src/vaults/interfaces/investments/ISyncDepositManager.sol
  src/vaults/legacy/LegacyVaultAdapter.sol
  test/vaults/integration/AssetShareConversion.t.sol
  test/vaults/integration/AsyncRequests.t.sol
  test/vaults/integration/Deposit.t.sol
  test/vaults/integration/DepositRedeem.t.sol
  test/vaults/integration/PoolManager.t.sol
  test/vaults/integration/Redeem.t.sol
  test/vaults/integration/SyncDeposit.t.sol
  test/vaults/integration/SyncRequests.t.sol
  test/vaults/integration/VaultRouter.t.sol
  test/vaults/mocks/MockCentrifugeChain.sol
  test/vaults/unit/VaultRouter.t.sol
Labels: :building_construction: refactor

#271 SCM: test fixes + improvements
  src/hub/Hub.sol
  src/hub/ShareClassManager.sol
  src/hub/interfaces/IShareClassManager.sol
  src/misc/libraries/ConversionLib.sol
  test/hub/unit/Holdings.t.sol
  test/hub/unit/ShareClassManager.t.sol
  test/misc/unit/libraries/ConversionLib.t.sol
Labels: v3: pre-audit

#303 fix: investment manager types
  src/vaults/AsyncVault.sol
  src/vaults/factories/AsyncVaultFactory.sol
  src/vaults/legacy/LegacyVaultAdapter.sol
Labels: annoyance, v3: pre-audit

#242 feat: Shareclass manager refactor
  foundry.toml
  script/adapters/Localhost.s.sol
  src/common/types/AssetId.sol
  src/hub/Holdings.sol
  src/hub/Hub.sol
  src/hub/HubRegistry.sol
  src/hub/ShareClassManager.sol
  src/hub/interfaces/IHoldings.sol
  src/hub/interfaces/IHub.sol
  src/hub/interfaces/IHubRegistry.sol
  src/hub/interfaces/IShareClassManager.sol
  src/misc/libraries/ConversionLib.sol
  test/hub/integration/BaseTest.sol
  test/hub/integration/Cases.t.sol
  test/hub/unit/Holdings.t.sol
  test/hub/unit/Hub.t.sol
  test/hub/unit/ShareClassManager.t.sol
  test/integration/EndToEnd.t.sol
  test/misc/unit/libraries/ConversionLib.t.sol
Labels: v3: pre-audit

#251 Feat: Balance Sheet with Queued Amounts
  src/common/MessageDispatcher.sol
  src/common/MessageProcessor.sol
  src/common/interfaces/IGatewayHandlers.sol
  src/common/interfaces/IGatewaySenders.sol
  src/common/libraries/MessageLib.sol
  src/hub/Hub.sol
  src/hub/interfaces/IHub.sol
  src/vaults/AsyncRequests.sol
  src/vaults/BalanceSheet.sol
  src/vaults/SyncRequests.sol
  src/vaults/interfaces/IBalanceSheet.sol
  test/common/unit/libraries/MessageLib.t.sol
  test/hub/mocks/MockVaults.sol
  test/hub/unit/Hub.t.sol
  test/vaults/integration/BalanceSheet.t.sol
  test/vaults/integration/Deposit.t.sol
Labels: v3: pre-audit

#320 refactor: rm ISharePriceProvider
  src/vaults/SyncRequests.sol
  src/vaults/interfaces/investments/ISharePriceProvider.sol
  src/vaults/interfaces/investments/ISyncRequests.sol
  test/vaults/integration/SyncRequests.t.sol
Labels: :building_construction: refactor

#327 chore: minor post mortem changes
  src/hub/Hub.sol
  src/vaults/BaseVaults.sol
  src/vaults/interfaces/IBaseVaults.sol
  test/vaults/integration/BalanceSheet.t.sol
  test/vaults/integration/SyncDeposit.t.sol
  test/vaults/unit/AsyncVault.t.sol
Labels: annoyance

#330 remove unused import
  src/common/interfaces/IGatewayHandlers.sol
Labels: :building_construction: refactor

#329 ref: Rename (A)SyncRequests to (A)SyncRequestManager
  deployments/testnet/sepolia.json
  deployments/verify.sh
  foundry.toml
  script/VaultsDeployer.s.sol
  snapshots/AsyncVault.json
  snapshots/VaultRouter.json
  src/common/libraries/PricingLib.sol
  src/vaults/AsyncRequestManager.sol
  src/vaults/AsyncVault.sol
  src/vaults/BaseVaults.sol
  src/vaults/SyncRequestManager.sol
  src/vaults/factories/AsyncVaultFactory.sol
  src/vaults/factories/PoolEscrowFactory.sol
  src/vaults/interfaces/investments/IAsyncRequestManager.sol
  src/vaults/interfaces/investments/IBaseInvestmentManager.sol
  src/vaults/interfaces/investments/ISyncRequestManager.sol
  src/vaults/legacy/LegacyVaultAdapter.sol
  test/hooks/integration/FreelyTransferable.t.sol
  test/integration/EndToEnd.t.sol
  test/vaults/BaseTest.sol
  test/vaults/integration/Admin.t.sol
  test/vaults/integration/AsyncRequestManager.t.sol
  test/vaults/integration/AsyncRequests.t.sol
  test/vaults/integration/BalanceSheet.t.sol
  test/vaults/integration/Deposit.t.sol
  test/vaults/integration/DepositRedeem.t.sol
  test/vaults/integration/PoolManager.t.sol
  test/vaults/integration/Redeem.t.sol
  test/vaults/integration/SyncDeposit.t.sol
  test/vaults/integration/SyncRequestManager.t.sol
  test/vaults/integration/VaultRouter.t.sol
  test/vaults/mocks/MockCentrifugeChain.sol
  test/vaults/unit/AsyncVault.t.sol
  test/vaults/unit/VaultRouter.t.sol
  test/vaults/unit/factories/PoolEscrowFactory.t.sol
  test/vaults/unit/factories/TokenFactory.t.sol
Labels: :building_construction: refactor

#331 Rename claim to notify in Hub side
  script/adapters/Localhost.s.sol
  src/hub/Hub.sol
  src/hub/interfaces/IHub.sol
  test/hub/integration/Cases.t.sol
  test/integration/EndToEnd.t.sol
Labels: :building_construction: refactor

#333 Docs: add diagrams
  docs/architecture/common.puml
  docs/architecture/deployers.puml
  docs/architecture/hub.puml
  docs/architecture/messaging.puml
  docs/architecture/vaults/managers.puml
  docs/architecture/vaults/overview.puml
  docs/architecture/vaults/vaults.puml
  docs/pools/architecture.puml
Labels: :book: documentation

#339 Fix: issueShares payment
  src/hub/Hub.sol
  test/hub/integration/BaseTest.sol
  test/hub/integration/Cases.t.sol
  test/hub/mocks/MockVaults.sol
  test/integration/EndToEnd.t.sol
Labels: :bug: bug, :white_check_mark: test
