Repository centrifuge/protocol, pull requests merged in 2025-10, with the labels that each got.

#653 normalize hub API params
  script/TestData.s.sol
  src/hub/Hub.sol
  src/hub/interfaces/IHub.sol
  test/hub/integration/Cases.t.sol
  test/hub/unit/Hub.t.sol
  test/integration/EndToEnd.t.sol
Labels: :building_construction: refactor

#346 Automated NAV manager + simple price manager
  docs/architecture/deployers.puml
  docs/architecture/hub.puml
  script/ExtendedHubDeployer.s.sol
  script/ExtendedSpokeDeployer.s.sol
  script/HubDeployer.s.sol
  script/HubManagersDeployer.s.sol
  script/SpokeManagersDeployer.s.sol
  script/utils/README.md
  src/common/types/AccountId.sol
  src/common/types/ShareClassId.sol
  src/hub/Hub.sol
  src/managers/hub/NAVManager.sol
  src/managers/hub/SimplePriceManager.sol
  src/managers/hub/interfaces/INAVManager.sol
  src/managers/hub/interfaces/ISimplePriceManager.sol
  src/managers/spoke/MerkleProofManager.sol
  src/managers/spoke/OnOfframpManager.sol
  src/managers/spoke/QueueManager.sol
  src/managers/spoke/README.md
  src/managers/spoke/decoders/BaseDecoder.sol
  src/managers/spoke/decoders/CircleDecoder.sol
  src/managers/spoke/decoders/VaultDecoder.sol
  src/managers/spoke/interfaces/IBalanceSheetManager.sol
  src/managers/spoke/interfaces/IMerkleProofManager.sol
  src/managers/spoke/interfaces/IMerkleProofManagerFactory.sol
  src/managers/spoke/interfaces/IOnOfframpManager.sol
  src/managers/spoke/interfaces/IOnOfframpManagerFactory.sol
  src/managers/spoke/interfaces/IQueueManager.sol
  test/hub/integration/BaseTest.sol
  test/managers/hub/Deployment.t.sol
  test/managers/hub/integration/NAVManager.t.sol
  test/managers/hub/unit/NAVManager.t.sol
  test/managers/hub/unit/SimplePriceManager.t.sol
  test/managers/spoke/Deployment.t.sol
  test/managers/spoke/integration/MerkleProofManager.t.sol
  test/managers/spoke/integration/OnOfframpManager.t.sol
  test/managers/spoke/integration/QueueManager.t.sol
  test/managers/spoke/libraries/MerkleTreeLib.sol
  test/managers/spoke/unit/OnOfframpManager.t.sol
  test/managers/spoke/unit/QueueManager.t.sol
Labels: v3.1

#649 Withdraw vaults subsidity
  script/VaultsDeployer.s.sol
  snapshots/AsyncVault.json
  snapshots/VaultRouter.json
  src/common/MessageDispatcher.sol
  src/spoke/libraries/UpdateContractMessageLib.sol
  src/vaults/AsyncRequestManager.sol
  src/vaults/interfaces/IVaultManagers.sol
  test/integration/EndToEnd.t.sol
  test/spoke/unit/libraries/UpdateContractMessageLib.t.sol
  test/vaults/Deployment.t.sol
Labels: :technologist: new feat

#660 ref: unify price variants
  script/TestData.s.sol
  src/common/MessageDispatcher.sol
  src/common/MessageProcessor.sol
  src/common/interfaces/IGatewaySenders.sol
  src/common/libraries/MessageLib.sol
  src/hub/Hub.sol
  src/hub/ShareClassManager.sol
  src/hub/interfaces/IShareClassManager.sol
  src/managers/hub/SimplePriceManager.sol
  src/managers/hub/interfaces/ISimplePriceManager.sol
  src/vaults/BatchRequestManager.sol
  src/vaults/interfaces/IBatchRequestManager.sol
  test/common/unit/libraries/MessageLib.t.sol
  test/hub/mocks/MockVaults.sol
  test/hub/unit/ShareClassManager.t.sol
  test/vaults/unit/BatchRequestManager.t.sol
Labels: :building_construction: refactor

#669 Idea: Allow nested withBatch calls for composibility
  src/core/Gateway.sol
  test/core/unit/Gateway.t.sol
Labels: :bulb: idea

#673 Move factory interfaces to correct places
  src/core/spoke/BalanceSheet.sol
  src/core/spoke/Spoke.sol
  src/core/spoke/VaultRegistry.sol
  src/core/spoke/factories/PoolEscrowFactory.sol
  src/core/spoke/factories/TokenFactory.sol
  src/core/spoke/factories/interfaces/IPoolEscrowFactory.sol
  src/core/spoke/factories/interfaces/ITokenFactory.sol
  src/core/spoke/factories/interfaces/IVaultFactory.sol
  src/core/spoke/interfaces/IBalanceSheet.sol
  src/core/spoke/interfaces/ISpoke.sol
  src/core/spoke/interfaces/IVaultRegistry.sol
  src/vaults/factories/AsyncVaultFactory.sol
  src/vaults/factories/SyncDepositVaultFactory.sol
  test/core/spoke/integration/BaseTest.sol
  test/core/spoke/unit/BalanceSheet.t.sol
  test/core/spoke/unit/Spoke.t.sol
  test/core/spoke/unit/VaultRegistry.t.sol
  test/core/unit/factories/PoolEscrowFactory.t.sol
Labels: :building_construction: refactor

#680 Fix: Gateway reentrancy issue
  src/core/Gateway.sol
  src/core/interfaces/IGateway.sol
  test/core/unit/Gateway.t.sol
Labels: :bug: bug

#696 ci: add ward check script
  .github/workflows/ci.yml
  script/utils/check_ward_coverage.py
  snapshots/AsyncVault.json
  snapshots/SyncDepositVault.json
  snapshots/VaultRouter.json
  test/integration/Deployer.t.sol
Labels: :white_check_mark: test

#705 Tests: Change `vm.assume` to `bound`s
  test/adapters/unit/AxelarAdapter.t.sol
  test/adapters/unit/LayerZeroAdapter.t.sol
  test/adapters/unit/WormholeAdapter.t.sol
  test/core/hub/unit/Accounting.t.sol
  test/core/spoke/unit/RestrictedTransfers.t.sol
  test/core/types/AssetId.t.sol
  test/core/types/PoolId.t.sol
  test/core/types/ShareClassId.t.sol
  test/hooks/unit/BaseTransferHook.t.sol
  test/managers/spoke/unit/OnOfframpManager.t.sol
  test/managers/spoke/unit/QueueManager.t.sol
  test/misc/unit/libraries/CastLib.t.sol
  test/misc/unit/libraries/D18.t.sol
  test/misc/unit/libraries/MathLib.t.sol
  test/vaults/unit/BatchRequestManager.t.sol
Labels: :white_check_mark: test

#707 fix: `MultiAdapter` uninitialized network view panic
  snapshots/AsyncVault.json
  snapshots/MessageGasLimits.json
  snapshots/SyncDepositVault.json
  snapshots/VaultRouter.json
  src/core/messaging/GasService.sol
  src/core/messaging/MultiAdapter.sol
  test/core/unit/MultiAdapter.t.sol
Labels: :bug: bug

#706 Minor changes in gateway batching docs
  src/core/messaging/interfaces/IGateway.sol
Labels: :book: documentation
