Repository centrifuge/protocol, pull requests merged in 2025-09, with the labels that each got.

#611 Ref: Move adapter manager to Gateway
  script/CommonDeployer.s.sol
  snapshots/AsyncVault.json
  snapshots/VaultRouter.json
  src/common/GasService.sol
  src/common/Gateway.sol
  src/common/Guardian.sol
  src/common/MessageDispatcher.sol
  src/common/MessageProcessor.sol
  src/common/MultiAdapter.sol
  src/common/interfaces/IAdapter.sol
  src/common/interfaces/IGateway.sol
  src/common/interfaces/IGatewaySenders.sol
  src/common/interfaces/IGuardian.sol
  src/common/interfaces/IMultiAdapter.sol
  src/common/libraries/MessageLib.sol
  src/hub/Hub.sol
  src/hub/interfaces/IHub.sol
  test/common/Deployment.t.sol
  test/common/unit/GasService.t.sol
  test/common/unit/Gateway.t.sol
  test/common/unit/Guardian.t.sol
  test/common/unit/MultiAdapter.t.sol
  test/common/unit/libraries/MessageLib.t.sol
  test/hub/Deployment.t.sol
  test/hub/unit/Hub.t.sol
  test/integration/EndToEnd.t.sol
  test/integration/adapters/LocalAdapter.sol
  test/spoke/Deployment.t.sol
  test/vaults/Deployment.t.sol
Labels: :building_construction: refactor

#613 root messages only from mainnet
  snapshots/AsyncVault.json
  snapshots/VaultRouter.json
  src/common/MessageProcessor.sol
  src/common/interfaces/IMessageProcessor.sol
  test/integration/utils/IntegrationConstants.sol
Labels: :technologist: new feat

#619 Feat: allow multiple gateway managers
  snapshots/AsyncVault.json
  snapshots/SyncDepositVault.json
  snapshots/VaultRouter.json
  src/common/GasService.sol
  src/common/Gateway.sol
  src/common/Guardian.sol
  src/common/MessageDispatcher.sol
  src/common/MessageProcessor.sol
  src/common/MultiAdapter.sol
  src/common/interfaces/IGasService.sol
  src/common/interfaces/IGateway.sol
  src/common/interfaces/IGatewayHandlers.sol
  src/common/interfaces/IGatewaySenders.sol
  src/common/interfaces/IGuardian.sol
  src/common/libraries/MessageLib.sol
  src/hub/Hub.sol
  src/hub/interfaces/IHub.sol
  src/misc/libraries/ArrayLib.sol
  src/spoke/Spoke.sol
  test/common/unit/Gateway.t.sol
  test/common/unit/Guardian.t.sol
  test/common/unit/libraries/MessageLib.t.sol
  test/hub/integration/Cases.t.sol
  test/hub/unit/Hub.t.sol
  test/integration/EndToEnd.t.sol
  test/integration/Integration.t.sol
  test/integration/fork/ForkTestInvestments.sol
  test/spoke/integration/BaseTest.sol
Labels: :technologist: new feat

#631 Sending messages while processing messages to unpaid
  snapshots/AsyncVault.json
  snapshots/VaultRouter.json
  src/common/Gateway.sol
  src/common/MessageDispatcher.sol
  src/common/MessageProcessor.sol
  src/common/interfaces/IGateway.sol
  src/common/interfaces/IGatewaySenders.sol
  src/hub/HubHandler.sol
  test/common/unit/Gateway.t.sol
  test/hub/Deployment.t.sol
  test/integration/EndToEnd.t.sol
  test/integration/ThreeChainEndToEnd.t.sol
  test/spoke/Deployment.t.sol
  test/vaults/Deployment.t.sol
Labels: :building_construction: refactor

#638 Revert "Idea: Permissionless batching by aux contract (#625)"
  script/CommonDeployer.s.sol
  src/common/CrosschainBatcher.sol
  src/common/interfaces/ICrosschainBatcher.sol
  test/common/Deployment.t.sol
  test/common/unit/CrosschainBatcher.t.sol
  test/hub/Deployment.t.sol
  test/hub/unit/Hub.t.sol
  test/spoke/Deployment.t.sol
  test/vaults/Deployment.t.sol
Labels: :building_construction: refactor

#633 tests: add manager permission checks for `BatchRequestManager`
  test/vaults/unit/BatchRequestManager.t.sol
Labels: :white_check_mark: test

#639 Tests: Reduce MockHubRequestManager imple
  test/hub/integration/BaseTest.sol
  test/hub/integration/mocks/MockHubRequestManager.sol
Labels: :white_check_mark: test

#645 Gateway with permissionless batch and multicall abstraction
  snapshots/AsyncVault.json
  snapshots/SyncDepositVault.json
  snapshots/VaultRouter.json
  src/common/BatchedMulticall.sol
  src/common/Gateway.sol
  src/common/interfaces/IBatchedMulticall.sol
  src/common/interfaces/IGateway.sol
  src/hub/Hub.sol
  src/hub/interfaces/IHub.sol
  src/spoke/BalanceSheet.sol
  src/spoke/interfaces/IBalanceSheet.sol
  src/vaults/VaultRouter.sol
  src/vaults/interfaces/IVaultRouter.sol
  test/common/unit/BatchedMulticall.t.sol
  test/common/unit/Gateway.t.sol
  test/hub/unit/Hub.t.sol
  test/spoke/unit/BalanceSheet.t.sol
Labels: :technologist: new feat, :building_construction: refactor

#646 Fix burrasec issue regarding gas process.
  snapshots/AsyncVault.json
  snapshots/VaultRouter.json
  src/common/Gateway.sol
  test/common/unit/Gateway.t.sol
Labels: :bug: bug
