Repository centrifuge/protocol, pull requests merged in 2025-06, with the labels that each got.

#426 chore: add `{Add, Remove}Vault events`
  src/spoke/interfaces/IVaultManager.sol
  src/vaults/BaseRequestManager.sol
Labels: v3

#432 ref: normalize PricingLib return types to `uint128`
  snapshots/AsyncVault.json
  snapshots/SyncDepositVault.json
  snapshots/VaultRouter.json
  src/common/libraries/PricingLib.sol
  src/hub/Holdings.sol
  src/hub/ShareClassManager.sol
  src/misc/IdentityValuation.sol
  test/hub/integration/Cases.t.sol
  test/hub/unit/ShareClassManager.t.sol
  test/misc/mocks/MockValuation.sol
  test/misc/unit/libraries/PricingLib.t.sol
Labels: :building_construction: refactor

#433 Tests: add more end-to-end tests
  src/common/libraries/PricingLib.sol
  src/spoke/BalanceSheet.sol
  test/common/mocks/MockValuation.sol
  test/hooks/mocks/MockSnapshotHook.sol
  test/hub/integration/BaseTest.sol
  test/integration/EndToEnd.t.sol
  test/integration/ThreeChainEndToEnd.t.sol
  test/misc/unit/libraries/PricingLib.t.sol
Labels: :white_check_mark: test

#350 On/offramp manager
  snapshots/AsyncVault.json
  snapshots/VaultRouter.json
  src/common/types/PoolId.sol
  src/managers/OnOfframpManager.sol
  src/managers/interfaces/IBalanceSheetManager.sol
  src/managers/interfaces/IOnOfframpManager.sol
  src/managers/interfaces/IOnOfframpManagerFactory.sol
  src/misc/interfaces/IERC165.sol
  src/misc/interfaces/IERC7575.sol
  src/spoke/libraries/UpdateContractMessageLib.sol
  test/managers/integration/OnOfframpManager.t.sol
  test/spoke/unit/libraries/UpdateContractMessageLib.t.sol
Labels: v3

#418 Tests: BalanceSheet UTs
  snapshots/AsyncVault.json
  snapshots/SyncDepositVault.json
  snapshots/VaultRouter.json
  src/hub/HubHelpers.sol
  src/spoke/BalanceSheet.sol
  src/spoke/Escrow.sol
  src/spoke/interfaces/IEscrow.sol
  src/vaults/AsyncRequestManager.sol
  src/vaults/VaultRouter.sol
  test/integration/EndToEnd.t.sol
  test/spoke/integration/BalanceSheet.t.sol
  test/spoke/unit/BalanceSheet.t.sol
Labels: :bug: bug, :white_check_mark: test

#445 Feat: BalanceSheet multicall
  script/SpokeDeployer.s.sol
  snapshots/AsyncVault.json
  snapshots/SyncDepositVault.json
  snapshots/VaultRouter.json
  src/spoke/BalanceSheet.sol
Labels: :technologist: new feat, v3

#450 Test: Finish BalanceSheet UTs
  src/spoke/BalanceSheet.sol
  test/spoke/integration/BalanceSheet.t.sol
  test/spoke/unit/BalanceSheet.t.sol
Labels: :white_check_mark: test

#419 Deployment Architecture Improvements
  .gitignore
  .sops.yaml
  deployments/deploy.sh
  deployments/testnet/sepolia.json
  docs/architecture/vaults/managers.puml
  env/arbitrum-sepolia.json
  env/arbitrum.json
  env/base-sepolia.json
  env/base.json
  env/ethereum.json
  env/example.json
  env/sepolia.json
  foundry.toml
  script/Adapters.s.sol
  script/CommonDeployer.s.sol
  script/FullDeployer.s.sol
  script/HubDeployer.s.sol
  script/SpokeDeployer.s.sol
  script/TestData.s.sol
  script/WireAdapters.s.sol
  script/adapters/Axelar.s.sol
  script/adapters/Wormhole.s.sol
  script/deploy/deploy.sh
  script/deploy/formathelper.sh
  script/deploy/load_vars.sh
  script/deploy/verify.sh
  script/utils/JsonRegistry.s.sol
  test/spoke/BaseTest.sol
  test/spoke/integration/VaultRouter.t.sol
  test/spoke/unit/VaultRouter.t.sol
Labels: :technologist: new feat, :building_construction: refactor, v3

#379 Add `MerkleProofManager`
  .github/workflows/ci.yml
  README.md
  docs/audits/2025-05-burraSec.pdf
  docs/audits/2025-05-xmxanuel.pdf
  script/utils/fix_imports.py
  src/managers/MerkleProofManager.sol
  src/managers/decoders/BaseDecoder.sol
  src/managers/decoders/CircleDecoder.sol
  src/managers/decoders/VaultDecoder.sol
  src/managers/interfaces/IMerkleProofManager.sol
  src/managers/interfaces/IMerkleProofManagerFactory.sol
  src/managers/interfaces/IOnOfframpManager.sol
  src/misc/libraries/MerkleProofLib.sol
  src/spoke/libraries/UpdateContractMessageLib.sol
  src/vaults/VaultRouter.sol
  test/managers/integration/MerkleProofManager.t.sol
  test/managers/libraries/MerkleTreeLib.sol
  test/misc/unit/libraries/MerkleProofLib.t.sol
  test/spoke/unit/libraries/UpdateContractMessageLib.t.sol
Labels: :technologist: new feat, v3.1

#459 Add `protected` modifier to `Hub.notifyDepositRedeem` methods
  src/hub/Hub.sol
Labels: :bug: bug, v3

#458 feat: wire adapters
  script/Adapters.s.sol
  script/CommonDeployer.s.sol
  script/WireAdapters.s.sol
  src/common/Guardian.sol
  src/common/interfaces/IGuardian.sol
  src/common/interfaces/adapters/IAxelarAdapter.sol
  src/common/interfaces/adapters/IWormholeAdapter.sol
  test/common/unit/AxelarAdapter.t.sol
  test/common/unit/Guardian.t.sol
  test/common/unit/WormholeAdapter.t.sol
  test/hub/integration/BaseTest.sol
  test/integration/EndToEnd.t.sol
  test/integration/ThreeChainEndToEnd.t.sol
  test/spoke/BaseTest.sol
Labels: :technologist: new feat, v3

#463 Docs: update diagrams
  docs/architecture/common.puml
  docs/architecture/hub.puml
  docs/architecture/vaults/managers.puml
Labels: :book: documentation

#466 Fix: normalize delta positive
  snapshots/AsyncVault.json
  snapshots/SyncDepositVault.json
  snapshots/VaultRouter.json
  src/spoke/BalanceSheet.sol
  test/spoke/unit/BalanceSheet.t.sol
Labels: v3

#473 Test: fix ITs with create3
  remappings.txt
  script/CommonDeployer.s.sol
  snapshots/AsyncVault.json
  snapshots/SyncDepositVault.json
  snapshots/VaultRouter.json
  test/spoke/BaseTest.sol
Labels: :white_check_mark: test

#475 Deploy: input config & fix end-to-end issues
  script/CommonDeployer.s.sol
  script/FullDeployer.s.sol
  script/HubDeployer.s.sol
  script/SpokeDeployer.s.sol
  test/common/Deployment.t.sol
  test/hub/Deployment.t.sol
  test/hub/integration/BaseTest.sol
  test/integration/EndToEnd.t.sol
  test/spoke/BaseTest.sol
  test/spoke/Deployment.t.sol
Labels: :white_check_mark: test

#480 Test: Fix deployment tests
  test/hub/Deployment.t.sol
  test/spoke/Deployment.t.sol
Labels: :white_check_mark: test

#481 Ref: split deployers
  docs/architecture/deployers.puml
  script/CommonDeployer.s.sol
  script/ExtendedSpokeDeployer.s.sol
  script/FullDeployer.s.sol
  script/HooksDeployer.s.sol
  script/HubDeployer.s.sol
  script/ManagersDeployer.s.sol
  script/SpokeDeployer.s.sol
  script/VaultsDeployer.s.sol
  test/hooks/Deployment.t.sol
  test/managers/Deployment.t.sol
  test/spoke/BaseTest.sol
  test/spoke/Deployment.t.sol
  test/vaults/Deployment.t.sol
Labels: v3

#484 Deploy: minor version/isTests changes
  script/Adapters.s.sol
  script/CommonDeployer.s.sol
  script/FullDeployer.s.sol
  script/utils/JsonRegistry.s.sol
  snapshots/VaultRouter.json
  test/common/Deployment.t.sol
  test/hub/integration/BaseTest.sol
  test/integration/EndToEnd.t.sol
  test/spoke/BaseTest.sol
Labels: v3
